---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-container-networking-tf
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Container networking via tf-operator
  sequenced: true
  chart_group:
    - tf-operator
