---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tf-operator
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: tf-operator-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.tf-operator
      dest:
        path: .source
    # Image versions
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.tf-operator
      dest:
        path: .values.images
    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .values.networking.podSubnet
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .values.networking.ipFabricSubnet
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.service_cidr
      dest:
        path: .values.networking.serviceSubnet
data:
  chart_name: tf-operator
  release: tf-operator
  namespace: atsgen
  protected:
    continue_processing: true
  wait:
    timeout: 600
    labels:
      release_group: airship-tf-operator
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-tf-operator
  values:
    clusterName: k8s
    networking:
      ipForwarding: snat
      useHostNewtorkService: true
